import Head from "next/head";
import { Text, Grid, Image, Button } from "@nextui-org/react";
import { CSSProperties } from "react";
import { BsBoxArrowUpRight, BsGithub } from "react-icons/bs";

// UX/UI
// COLLECTION
// Hi, adventurer.
// This is place where I study UI/UX, design system and implement what I learned.
// Ready? Let's start !

export default function Home() {
  const pageStyle: CSSProperties = {
    background: "url('/glassmorphism-background.png')",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    padding: "5%",
  };
  return (
    <>
      <Head>
        <title>UI/UX collection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div
          className="h-screen flex flex-col justify-center"
          style={pageStyle}
        >
          <Grid.Container
            gap={5}
            className="bg-white/50 m-50 rounded-lg shadow-2xl"
          >
            <Grid xs={7} className="flex flex-col">
              <div>
                <Text h1 size={60} weight="bold">
                  UI/UX
                  <br />
                  COLLECTION
                </Text>
              </div>
              <div className="mt-2">
                <Text>
                  Hi, adventurer.
                  <br />
                  This is place where I study UI/UX, design system and implement
                  what I learned.
                  <br />
                  Ready? Let's start !
                </Text>
              </div>
              <div className="mt-8 flex flex-row">
                <Button className="bg-orange-700">
                  <BsBoxArrowUpRight className="mr-2"/>
                  Explore now
                </Button>
                <span className="mx-5 my-auto">or</span>
                <Button className="bg-gray-400/30 text-orange-600" style={{border: "2px solid #ea580c"}}>
                  <BsGithub className="mr-2" color="black"/>
                  View source
                </Button>
              </div>
            </Grid>
            <Grid xs={5}>
              <Image src="/image-cover.png" />
            </Grid>
          </Grid.Container>
        </div>
      </main>
    </>
  );
}
