import Head from "next/head";
import { Text, Grid, Image, Button } from "@nextui-org/react";
import { CSSProperties, useEffect, useState } from "react";
import { BsBoxArrowUpRight, BsGithub } from "react-icons/bs";
import useMedia from "../repositories/useMedia";
import * as h from "../styles/Home.module.css";

export default function Home() {
  const [text, setText] = useState<string>("");
  const pageStyle: CSSProperties = {
    background: "url('/glassmorphism-background.png')",
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    padding: "5%",
  };
  const isMobile = useMedia("(max-width: 400px)");
  const onViewSource = function () {
    window.open("https://github.com/duccanhole/ui-ux-collection", "_blank");
  };
  useEffect(() => {
    const timeout = setTimeout(() => {
      setText((val) => val + "a");
    }, 800);
    return () => clearTimeout(timeout);
  }, [text]);
  return (
    <>
      <Head>
        <title>UI/UX collection</title>
        <link rel="icon" type="image/x-icon" href="/landing-page.ico"></link>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div
          className="h-screen flex flex-col justify-center"
          style={pageStyle}
        >
          <Grid.Container
            gap={5}
            className="bg-white/50 m-50 rounded-lg shadow-2xl"
          >
            <Grid md={7} sm={10} className="flex flex-col">
              <div>
                <Text h1 size={isMobile ? 40 : 60} weight="bold">
                  UI/UX
                  <br />
                  COLLECTION
                </Text>
              </div>
              <div className="mt-2">
                <Text
                  size={20}
                  className={`${h.default.typed} ${h.default.typed1}`}
                >
                  Hi, adventurer.
                </Text>
                <Text
                  size={20}
                  className={`${h.default.typed} ${h.default.typed2}`}
                >
                  This is place where I study UI/UX, design system and implement
                  what I learned.
                </Text>
                <Text
                  size={20}
                  className={`${h.default.typed} ${h.default.typed3}`}
                >
                  Ready? Let's start !
                </Text>
              </div>
              <div className="mt-6 flex flex-wrap">
                <Button className="mt-2 bg-orange-700">
                  <BsBoxArrowUpRight className="mr-2" />
                  Explore now
                </Button>
                <span className="mx-5"></span>
                <Button
                  className="mt-2 bg-gray-400/30 text-orange-600"
                  style={{ border: "2px solid #ea580c" }}
                  onPress={onViewSource}
                >
                  <BsGithub className="mr-2" color="black" />
                  View source
                </Button>
              </div>
            </Grid>
            <Grid md={5} sm={10}>
              <Image src="/image-cover.png" />
            </Grid>
          </Grid.Container>
        </div>
      </main>
    </>
  );
}
