import Head from "next/head";
import { Inter } from "@next/font/google";
import { Card, Grid, Image } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>UI/UX collection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-blue-300 h-screen">
        <Grid.Container gap={2}>
          <Grid xl={5}>
            <Card isPressable variant="flat">
              <Image src="/psychedelic-eye-paint.jpg" alt="" />
            </Card>
          </Grid>
          <Grid xl={7}>
            <Card isPressable>
              <Card.Header className="font-bold text-6xl float-right">
                UX/UI<br/>COLLECTION
              </Card.Header>
              <Card.Body>
                Hi, adventurer.
                <br/>
                This is place where I study UI/UX, design system and implement what I learned.
                <br/>
                Ready? Let's start !
              </Card.Body>
            </Card>
          </Grid>
        </Grid.Container>
      </main>
    </>
  );
}
